Added more data-types
nanoblox/core pull request #49
Opened 2020-10-09 18:50 UTC by optimisticside

I've added a few more data-types to the serializer.

2020-10-09 18:53 UTC, optimisticside commented
The formatting is messed up right now

2020-10-10 11:17 UTC, 1ForeverHD requested changes

2020-10-10 11:17 UTC, 1ForeverHD commented on Projects/DataStore+/src/Serializer.lua
> +local function multiSplit(value)
This function needs to go above the table as its local!

2020-10-10 11:17 UTC, 1ForeverHD commented on Projects/DataStore+/src/Serializer.lua
> +		identifier = "e",
This identifier has already been taken by enum

2020-10-10 11:17 UTC, 1ForeverHD commented on Projects/DataStore+/src/Serializer.lua
> +		identifier = "w",
This identifier has already been taken by Vector2

2020-10-10 11:17 UTC, 1ForeverHD commented on Projects/DataStore+/src/Serializer.lua
> +			local x, y = Serializer.serialize(components[1]), Serializer.serialize(components[2])
Why are values serialized here when being deseralized?

2020-10-10 11:17 UTC, 1ForeverHD commented on Projects/DataStore+/src/Serializer.lua
> +			local origin, direction = Serializer.serialize(components[1]), Serializer.serialize(components[2])
Why are values serialized here when being deseralized?

2020-10-10 16:55 UTC, optimisticside commented
These should be fixed now

2021-02-02 10:27 UTC, closed without merging